name: Stale Branches
description: Sends a Slack message about stale branches
inputs:
  days-before-stale:
    description: "The number of days before a branch is considered stale"
    required: true
    default: "30"
  slack-webhook-url:
    description: "The Slack webhook URL to send the message to"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
