name: Release commits
description: Sends a Slack message about release commits
inputs:
  release-branch:
    description: "The release branch to compare"
    required: true
  previous-tag:
    description: "The previous release tag to compare against"
    required: true
  slack-webhook-url:
    description: "The Slack webhook URL to send the message to"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
